[workspace]
resolver = "2"
members = [
  "net_prowler_scanner",
  "net_prowler_cli"]

[workspace.dependencies]
cidr = "0.2.2"
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3.30"
itertools = "0.13.0"