[package]
name = "net_prowler_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
cidr.workspace = true
net_prowler_scanner = { path = "../net_prowler_scanner" }
tokio.workspace = true
