[package]
name = "net_prowler_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr.workspace = true
tokio.workspace = true
futures.workspace = true
itertools.workspace = true
socket2.workspace = true
etherparse.workspace = true